### ISSUE TITLE
Venv Selector issue with nightly build

### ISSUE THREAD

**Issue by Redoxahmii** [linux-cultist/venv-selector.nvim#100]
I have been using this plugin with LazyVim configuration for a while and it works stable but recently switching to the nightly build it does not work anymore.
Before opening any buffer if i use `VenvSelect` to select on nightly build it works then but if i have already opened a buffer for a file then it does not work. and results in showing errors.
![Screenshot from 2024-02-29 02-40-07](https://github.com/linux-cultist/venv-selector.nvim/assets/13983258/4a679fc2-b81c-46f5-98d7-5ad35d5df30a)

Keep in mind this is only happening on nightly build `0.10`.

**Comment by neolooong** [comment]
Try this https://github.com/linux-cultist/venv-selector.nvim/pull/99.

**Comment by linux-cultist** [comment]
> Try this #99.

Yeah it seems the PR would fix this. Just need to get it merged ASAP.

**Comment by Redoxahmii** [comment]
> > Try this #99.
> 
> Yeah it seems the PR would fix this. Just need to get it merged ASAP.


I will wait for the merge then.

**Comment by Redoxahmii** [comment]
It is resolved now and working on both versions correctly.

**Comment by linux-cultist** [comment]
Perfect. 👍 Thanks again to @neolooong!
