### ISSUE TITLE
Default pipenv path on Windows is wrong

### ISSUE THREAD

**Issue by bruce3x** [linux-cultist/venv-selector.nvim#102]
> [pipenv source code](https://github.com/pypa/pipenv/blob/main/pipenv/utils/shell.py#L187)

The default path for pipenv on Windows should be `'~\\.virtualenvs'`

**Comment by linux-cultist** [comment]
Thanks for reporting, will change it ASAP. 👍

**Comment by linux-cultist** [comment]
Fixed. :+1:
