### ISSUE TITLE
how do i select virtual env from WSL (windows subsystem from linux) in Windows Neovim?

### ISSUE THREAD

**Issue by ayushxx7** [linux-cultist/venv-selector.nvim#103]
I think this may not be right repo for this question, but someone might know.

I have a setup such that my nvim config is in Windows and it works well.
I tried setting up a duplicate config in WSL, and after much trial, most things work, except LSP.

When I clone repos, I clone then in Windows, but most of the times, I have to work within WSL to actually get things to run. For instance, I have to create my venv in WSL. This means that though my LSP can do most things, it can't figure out libraries I have installed in my WSL venv. 

Any help is appreciated!

**Comment by linux-cultist** [comment]
Maybe some windows user can give input on this. I don't have a windows machine myself and don't know the WSL very well.

**Comment by linux-cultist** [comment]
This is an old issue and hopefully you figured out a way to do this by now. Closing it. :)
