### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by pleaseletmesearch** [linux-cultist/venv-selector.nvim#107]
Hi - would you mind please licensing this repo? As it stands, in fact nobody's even allowed to clone it as far as I can see. (https://choosealicense.com/ is a simple point-and-click flow to choose one; extensive docs from GitHub at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository .)

**Comment by linux-cultist** [comment]
Of course, good idea. Let me read through that link and pick whatever licence is the most open. :)

**Comment by pleaseletmesearch** [comment]
(Personally I use MIT as my default "maximally open".)
