### ISSUE TITLE
Conda Env not activating

### ISSUE THREAD

**Issue by Abstruse-AK47** [linux-cultist/venv-selector.nvim#111]
Hi author,
Thank you for this wonderful plugin, which helps me a lot, but I meet some problems here.
When I trigger the VenvSelect command with the defined keymap, the envs menu will popup, all this is working properly.
![Screenshot 2024-04-14 161808](https://github.com/linux-cultist/venv-selector.nvim/assets/36753342/96920afe-6fb1-47ac-8f61-2de0e6f85cd0)

When i select .venv(virtual env) everthing works fine as intended, but if i select the other env(C-env,conda env), it doesn't initialize.
I get this message with "enable_debug_output = true"
![Screenshot 2024-04-14 161459](https://github.com/linux-cultist/venv-selector.nvim/assets/36753342/88278bb9-7233-490c-b6e2-450727b878cb)
Here is my config 
![Screenshot 2024-04-14 161555](https://github.com/linux-cultist/venv-selector.nvim/assets/36753342/f5817626-3c76-4ccf-a404-9027aefa77c6)

**Comment by Abstruse-AK47** [comment]
Resolved this issue don't know how. I installed this [nvim-conda](https://github.com/kmontocam/nvim-conda?tab=readme-ov-file#commands) and then tried to activate my environment again with :VenvSelect and it worked.
Issue Resolved

**Comment by linux-cultist** [comment]
Thank you for posting the solution too, will probably help someone else in the future. :)
