### ISSUE TITLE
Error spawning language server with cmd

### ISSUE THREAD

**Issue by steakhutzeee** [linux-cultist/venv-selector.nvim#118]
Hi, I'm experiencing the following running regexp branch.

I have a python file open, then with Telescope select another file and open it in a vertical split.

At the bottom I see:

```
Registered '/home/user/.venv/project/bin/python' with basedpyright LSP.
Registered '/home/user/.venv/project/bin/python' with basedpyright LSP.
Press ENTER or type command to continue
Spawning language server with cmd: `ruff-lsp` failed. The language server is either not installed, missing from PATH, or not executable.
Press ENTER or type command to continue
```

This does not happen if I open the files one at a time.

I actually use mason with mason-lspconfig and ruff-lsp/pyright are both correctly installed as I can see them under :LspInfo.

Any idea why?

**Comment by steakhutzeee** [comment]
Very strange, don't think the issue was related to this plugin btw. Just reinstalled ruff-lsp with Mason seems to have fixed it.

**Comment by linux-cultist** [comment]
Thank you. Sometimes its hard to know what is causing issues in neovim, we all use so many plugins. :)
