### ISSUE TITLE
[regexp] Disable notification

### ISSUE THREAD

**Issue by steakhutzeee** [linux-cultist/venv-selector.nvim#119]
Hi,

is there a way to disable notification on activation? For main branch there is `notify_user_on_activate` but that looks like not working with the new branch.

Thanks!

**Comment by linux-cultist** [comment]
Not yet but that's easy to add, will do it this weekend. Thanks for the feedback! Let me know anything else you think can be improved. Always nice.

**Comment by steakhutzeee** [comment]
Thank you!

A handy addition would be to have the notification only when the venv changes. So if I open a file I see the notification and if I open another file using the same venv I do not see it. Don't know if it's feasible.

**Comment by linux-cultist** [comment]
I added the config option `notify_user_on_venv_activation` that can be set to `false` to avoid the message. :)

In theory its possible to keep a list of previous opened venvs and just notify if its a new venv, but not sure if its worth the extra code. Also I suspect some people will probably report it as a bug if it only notifies sometimes and they didnt read about all the options.... :)

**Comment by steakhutzeee** [comment]
Just tested. Thank you very much :D
