### ISSUE TITLE
Can't find any pyenv virtual environments on new version

### ISSUE THREAD

**Issue by joebonneau** [linux-cultist/venv-selector.nvim#132]
Hi,

I tried switching over to the new version of the plugin, but I can't seem to get it set up such that my pyenv venvs are discovered. I'm on Mac and they're all located in the default location, ~/.pyenv/versions. Any ideas?

Thanks!

**Comment by linux-cultist** [comment]
Hi,

Interesting. Can you list the files under `~/.pyenv/versions`? I think that will give us some clue what's going on.

Just want to understand why it's not picking them up. It's good that you are on a mac, I haven't been able to test on a mac myself so I assumed it would work the same as on Linux. But maybe not. :)

**Comment by joebonneau** [comment]
Here's what I see:

<img width="1402" alt="image" src="https://github.com/linux-cultist/venv-selector.nvim/assets/68512346/847e124b-b02b-45f4-b6d5-adef7bb4ecbc">

Appears that everything but the python versions installed by pyenv (which I do see in the selector) are symlinks, and those symlinks are to environments located within those installations.

**Comment by linux-cultist** [comment]
Oh I think I understand now. The plugin needs to list symbolic links in that path and also don't expect them to end with the python name. I will fix this tomorrow, thanks for reporting it in. :)

**Comment by joebonneau** [comment]
Awesome, glad that was straightforward for you!

Also, thanks for creating this plugin. I was surprised how much trouble I had getting my venv to activate properly within my nvim instance before finding it. Appreciate your work.

**Comment by linux-cultist** [comment]
Update the plugin and try now please. :) I changed the default `fd` pyenv search to include all virtual envs created by it now. It should include all symlinks now also.

![image](https://github.com/linux-cultist/venv-selector.nvim/assets/126409588/39edcf28-6204-42b2-a563-b0f749004831)

**Comment by joebonneau** [comment]
Works as expected now! Thanks for the quick fix.
