### ISSUE TITLE
[Feature Request] Add VenvSelectCached command in regexp version

### ISSUE THREAD

**Issue by TroySigX** [linux-cultist/venv-selector.nvim#133]
Usually, I only open python files just to copy some functions without editing it, so enabling activating cached venv is overkill for me. But I do like to select cached venv when I edit them, so it'd be great if I have a choice to select cached venv when needed.

**Comment by linux-cultist** [comment]
I can add an option for this also, so the `VenvSelectCached` command shows up when the option is set. :)

**Comment by linux-cultist** [comment]
Update the plugin and set this option below to false:

`cached_venv_automatic_activation = false`

Then venvs should no longer be activated from cache automatically, and you need to run the `VenvSelectCached` command. 

Thanks for your feedback on this, appreciate it. :)
