### ISSUE TITLE
[Feature Request] Allow searches on discontinuous characters

### ISSUE THREAD

**Issue by TroySigX** [linux-cultist/venv-selector.nvim#134]
![image](https://github.com/linux-cultist/venv-selector.nvim/assets/88051085/4e96bd56-16d5-40ea-a05c-47b3bdbafd9c)

In my case, I'd like the picker to show the `cs589-hw4` venv when I type 5894. `main` branch can do this, but not `regexp` branch.

**Comment by linux-cultist** [comment]
Hi,

Thanks for the suggestion! I did change the default filtering in the `regexp` branch to match all characters, but going back to the previous filtering can easily be made into an option you can set. Thanks for the suggestion!

**Comment by TroySigX** [comment]
Thank you! Really appreciate it.
