### ISSUE TITLE
Add ability to activate venv without running lsp server 

### ISSUE THREAD

**Issue by igrikus** [linux-cultist/venv-selector.nvim#138]
I work with projects that don't even contain Python files, but still I need venv (ansible, awscli are mostly installed via pip) 

On the old version I had a startup function that activated cached venv, and I could use CLI tools directly from the nvim terminal

On the new version I have to open (create) a temporary python file for the same logic. This doesn't work for me at all :(

**Comment by igrikus** [comment]
This is my auto-activation code from old version, just for reference:
```lua
vim.api.nvim_create_autocmd("VimEnter", {
  desc = "Auto select virtualenv Nvim open",
  pattern = "*",
  callback = function()
    local venv = vim.fn.finddir("venv", vim.fn.getcwd())
    if venv ~= "" then
      require("venv-selector").retrieve_from_cache()
    end
  end,
  once = true,
})
```

**Comment by linux-cultist** [comment]
Oh I see. There are always usecases I dont consider out there. :)

The new version automatically activates the venv for the `vim.fn.getcwd()` but only if a python file is opened, like you said. 

But it would be nice if the plugin was more flexible and set the paths from a cached venv if there is one. It could skip the activation of the lsp if there is no python file opened and do everything else.

I will have a look at the code and see what can be done.

**Comment by linux-cultist** [comment]
In the latest commit, you can set the option `require_lsp_activation = false` and the plugin will still set env variables even if it hasnt activated a lsp. Please try it out. :)

**Comment by igrikus** [comment]
Thank you @linux-cultist,

Now I can **manually** activate my env with `VenvSelect` command
However, to load cached venv automatically I still need to open some Python file 😢 

I understand that I can use my [old autocmd approach above](https://github.com/linux-cultist/venv-selector.nvim/issues/138#issuecomment-2152860996), but maybe it can be done out of the box?

Should I open the new issue, or is it not planned due to available workarounds?

**Comment by linux-cultist** [comment]
Hi,

The plugin only tries to load a cached venv when you open a python file, or when you use the `VenvSelectCached` command. So you use the `VenvSelectCached` command I assume, and it doesnt set any env variables? Do you see anything in the debug log?

**Comment by igrikus** [comment]
I don't have the `VenvSelectCached` command. Is this normal or am I missing something?

I have enabled the logs in plugin config and call them with the `VenvSelectLog` command, but they are empty until I either open the python file or execute `VenvSelect`

**Comment by linux-cultist** [comment]
There is an option for enabling the `VenvSelectCached` command. It's for people who wants to run it manually and not have the plugin run it for them. You can find it in the Readme under options if you are interested in trying it. :) 

But ok, then I understand why cached venvs don't activate for you. The plugin doesn't do anything until you open a python file, or run a command. Its not designed to work without python files, since the venv gets registered with the lsp server for python.

But if you have that autocommand, you should be able to make it run `VenvSelectCached` on some vim action yourself. :)
