### ISSUE TITLE
Activate the environment using pyenv.

### ISSUE THREAD

**Issue by andresbermeoq** [linux-cultist/venv-selector.nvim#140]
Hi @linux-cultist, I tried to implement the plugin. I use poetry and pyenv in the most of my projects, but in some cases only recognizes the poetry environments. I use the parents to search in the global folder. I see all environments, but I show the next warning:

WARNING:
**VenvSelect: The python path '/home/andresbermeo/.pyenv/versions/3.9.18/lib/python3.9/venv/bin/python' doesnt exist.**

MY CONFIGURATION VENV-SELECTOR:
**venv_selector.setup({
  parents = 3,
  stay_on_this_version = true,
})**

**Comment by linux-cultist** [comment]
Hi,

I think you should switch to the new, rewritten version of VenvSelect in the `regexp` branch. It doesn't have these kind of bugs. They were a result or the plugin growing way beyond its original codebase while trying to stay backwards compatible. 

Check the Readme at the top. :)

**Comment by andresbermeoq** [comment]
Thanks @linux-cultist. I try to change the branch.
