### ISSUE TITLE
how to find the rye venv

### ISSUE THREAD

**Issue by newdee** [linux-cultist/venv-selector.nvim#143]
hello, I use [rye](https://github.com/astral-sh/rye) to manage python package, it always in .venv  folder, but I can not find it when coding. this plugin is very useful, so, I would like to know how to use the Rye Python environment in Vim. thanks!

**Comment by newdee** [comment]
I just add .venv folder to name, and it seems work, thanks again

**Comment by newdee** [comment]
f

**Comment by linux-cultist** [comment]
Hi,

Yeah sounds like it should work on old version. But if you try the new version of VenvSelect, it will be found automatically. You should switch over to it if you have time, since it's where new updates take place. :) See the Readme at the top for more info. Enjoy the plugin!

**Comment by newdee** [comment]
> Hi,
> 
> Yeah sounds like it should work on old version. But if you try the new version of VenvSelect, it will be found automatically. You should switch over to it if you have time, since it's where new updates take place. :) See the Readme at the top for more info. Enjoy the plugin!

Yes, thanks, I already did that ::smile::
