### ISSUE TITLE
Plugin can find venv's but activating them results in file `python` with gibberish content

### ISSUE THREAD

**Issue by guyonmatteau** [linux-cultist/venv-selector.nvim#144]
Hi! I am trying to setup the plugin with Lua. Installation seems to work, and it also lists a set of virtual envs (virtualenv, Poetry, etc). However when I hit enter on a selected virtual env a file opens with name `python` with the gibberish content:
```
Ïúíþ@ H__PAGEZERO8__TEXT@@__text__TEXT??__stubs__TEXT??__unwind_info__TEXT¨?X¨?__DATA_CONST@@@@__got__DATA_CONST@@H__LINKEDIT@4h3h X(P

P /usr/lib/dyldâ3ÂSù8L¥ÚÙANw2 
÷*(?hÿ/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation`

/Users/user/.pyenv/versions/3.10.13/lib/libpython3.10.dylibH

/opt/homebrew/opt/gettext/lib/libintl.8.dylib88/usr/lib/libSystem.B.dylib@/Users/user/.pyenv/versions/3.10.13/lib /opt/homebrew/lib&)°@ùÖ?@@?@ PX@@_Py_BytesMain__mh_execute_header$?d*ddf(èKe.?$?$N?d __mh_execute_header_Py_BytesMain_main/var/folders/29/gb84vhfs0mqfc98tbtjnvvpw0000gn/T/python-build.20231108205650.25335/Python-3.10.13/Programs/python.c/private/var/folders/29/gb84vhfs0mqfc98tbtjnvvpw0000gn/T/python-build.20231108205650.25335/Python-3.10.13/Programs/python.o_mainúÞÀúÞcX	 python.exe×"§©CwÆ¯8êÓM³gÁ\;SD¼>ní­¬²XoÆéfÀ×ÑÑkOXÿ|´|zÚ½H,§­¬²XoÆéfÀ×ÑÑkOXÿ|´|zÚ½H,§?Ê²¨ãtï,2l³#ûtL2xE­zr³jÄLÁßÕëñf¡,6ôcfñ
¸Ôî£Ò[àå´í­¬²XoÆéfÀ×ÑÑkOXÿ|´|zÚ½H,§­¬²XoÆéfÀ×ÑÑkOXÿ|´|zÚ½H,§­¬²XoÆéfÀ×ÑÑkOXÿ|´|zÚ½H,§BîK]üµùÕ<¬:$©g¾k|&h­áØô¨á
```
Seems to be some sort of encoding issue? I'm on Mac Sonoma 14.1 with a bash shell, Python 3.10 or 3.12, with the plugin selector as described in the README. I verified in `lazy-lock.json` that the commit is corresponding to the `regexp` branch, so the plugin should be up-to-date. 
```
return {
  "linux-cultist/venv-selector.nvim",
  dependencies = {
    "neovim/nvim-lspconfig",
    "mfussenegger/nvim-dap",
    "mfussenegger/nvim-dap-python", --optional
    { "nvim-telescope/telescope.nvim", branch = "0.1.x", dependencies = { "nvim-lua/plenary.nvim" } },
  },
  lazy = false,
  branch = "regexp", -- This is the regexp branch, use this for the new version
  config = function()
    require("venv-selector").setup()
  end,
  keys = {
    { ",v", "<cmd>VenvSelect<cr>" },
  },
}
```

Any idea?

**Comment by linux-cultist** [comment]
Wow that sounds really weird. It looks like it's opening your python executable instead of executing it. This looks like some problem with the python installation, but I don't know exactly what it can be. I don't think it's a problem with the plugin, other Mac users are using it without problems too. Maybe you are missing execute premissions on the python interpreter?

**Comment by linux-cultist** [comment]
Did you manage to figure out what is causing your python to be opened rather than executed? I would check if it's executable but it should be by default on installation with brew.

**Comment by linux-cultist** [comment]
Closing this since I dont think its a plugin issue.

**Comment by linux-cultist** [comment]
Hi @guyonmatteau ,

It seems I was wrong about it not being a plugin issue. Just now someone made a PR that I think will fix this issue. Can you update the plugin and see if it has fixed your issue? Thanks in advance.
