### ISSUE TITLE
Feature Request: Support pixi virtual environments

### ISSUE THREAD

**Issue by DevonPeroutky** [linux-cultist/venv-selector.nvim#149]
Like the title says, [pixi](https://github.com/prefix-dev/pixi) is another great package manager for python currently gaining steam. Would love to be able select venv's created through it

**Comment by linux-cultist** [comment]
If you try the new regexp branch of the plugin, odds are that they will just be found automatically. If they are in some special location, you can add your own search also. :) See the Readme at the top for links to regexp version.

**Comment by DevonPeroutky** [comment]
The new branch did work! Thanks.
