### ISSUE TITLE
Spaces in path prevent venv's from being displayed in telescope

### ISSUE THREAD

**Issue by themvl** [linux-cultist/venv-selector.nvim#150]
I noticed when theres a space in the full path of a venv it does not get detected or displayed. I was able to resolve an issue like this by replacing a space somewhere in a higher folder with a underscore.

**Comment by linux-cultist** [comment]
This is in the old version of the plugin right? You should try the new version in the regexp branch. It's rewritten from scratch and shouldn't have this problem.

**Comment by themvl** [comment]
AFAIK i actually am using the regexp version. As this is the default in lazyvim which i am using, as referenced here: https://www.lazyvim.org/extras/lang/python 

{
  "linux-cultist/venv-selector.nvim",
  branch = "regexp", -- Use this branch for the new version
  cmd = "VenvSelect",
  enabled = function()
    return LazyVim.has("telescope.nvim")
  end,
  opts = {
    settings = {
      options = {
        notify_user_on_venv_activation = true,
      },
    },
  },
  --  Call config for python files and load the cached venv automatically
  ft = "python",
  keys = { { "<leader>cv", "<cmd>:VenvSelect<cr>", desc = "Select VirtualEnv", ft = "python" } },
}

**Comment by AZenat** [comment]
I also have this issue on windows.
When one of the parent directory has a space, it doesn't find the virtual environments located in the current folder.

**Comment by kiryph** [comment]
I am on macOS/Darwin using the new branch regex and also noticed issues with searches of

- workspace
- cwd
- file

when paths contain spaces.

The unquoted environment variables $CWD, $WORKSPACE, $FILE_DIR in 

https://github.com/linux-cultist/venv-selector.nvim/blob/regexp/lua/venv-selector/config.lua#L94-L100

could be a problem.

When the searches `workspace`, `cwd`, and `file` point to the same venv, are they show separately or only one of them?
