### ISSUE TITLE
Warning on opening nvim every time

### ISSUE THREAD

**Issue by Murdock135** [linux-cultist/venv-selector.nvim#151]
Whenver I open neovim, I get this message:

"VenvSelect: This plugin has a new 2024 version that was rewritten from scratch to support user defined searches: https:/VenvSelect: Its highly recommended to upgrade, but if you want to stay on this version, you can set the option 'stay_on_this_version' to true. Only the new version will receive updates. "

Even though I'm using the latest repo for the plugin.
![image](https://github.com/linux-cultist/venv-selector.nvim/assets/79624449/773fec09-f165-47b9-9fd7-304496919f5c)

Here's my config for this plugin.

![image](https://github.com/linux-cultist/venv-selector.nvim/assets/79624449/ab4dcab9-190a-4062-b005-778c036ef235)

I literally just copy-pasted the code from the project's readme.md

How can I make it so that I don't get this message on startup?

**Comment by linux-cultist** [comment]
Hi,

There is a rewritten version of VenvSelect in the `regexp` branch that is much improved. :) Please check out the instructions in the Readme at the top and click the link to the regexp version. There you have installation instructions, reasons why we needed a rewrite and so on.

I think you will like the new cedi so! It's much simpler to understand and much more flexible, usually finding your venvs with no custom configuration. Hope you like it. :)
