### ISSUE TITLE
 Configuring "venv-selector" to use Conda Environment cannot find pyhon.exe

### ISSUE THREAD

**Issue by 123abch** [linux-cultist/venv-selector.nvim#153]
### Issue Description

When using `venv-selector` with Conda environments on Windows, the plugin looks for `python.exe` in the `Scripts` directory by default. However, Conda environments place `python.exe` directly in the environment directory, not in `Scripts`.

### Steps to Reproduce

1. Configure `venv-selector` to use a Conda environment.
2. Try to activate the environment.
3. Observe the error message indicating `python.exe` could not be found in the `Scripts` directory.

### Suggested Fix

Modify the system.lua to look for `python.exe` directly in the environment directory. Here is the modified code:

```lua
function M.get_python_parent_path()
  local config = require 'venv-selector.config'
  local parent_dir = config.settings.anaconda.python_parent_dir

  if M.sysname == 'Linux' or M.sysname == 'Darwin' then
    return parent_dir or 'bin'
  else
    return parent_dir or '.\\'
  end
end

This change allows the plugin to correctly locate python.exe in Conda environments.
Environment Details
OS: Windows 11
Neovim Version: 0.10.0
Plugin Version: latest

**Comment by linux-cultist** [comment]
Hi,

This should be fixed in a much better way in the `regexp` version of the plugin. It doesn't attempt to combine paths and guess where things are anymore. Also it lets you create your own searches if you need them. Please try it, there is info in the github readme at the top.
