### ISSUE TITLE
Pipenv environments are not listed

### ISSUE THREAD

**Issue by metal3d** [linux-cultist/venv-selector.nvim#155]
Hello,

I started to use a "poetry" project but I decided to use "pipenv" now. I removed the "pyproject.toml", the "~/.cache/poetry/..." directory and I know have a "Pipfile" inside my project.

Whatever I do, when I open a python file, VenvSelector creates a popup saying that it uses the poetry virtualenv (which is deleted)

![image](https://github.com/user-attachments/assets/b01e0ef4-a063-49d7-8d49-db2995e6f886)

And no venv is found if I want to switch:

![image](https://github.com/user-attachments/assets/29d77fff-4936-4e75-90a7-08837c6a72e0)

**Comment by metal3d** [comment]
I removed the `~/.cache/venv-selector` to fix the first problem. The second problem remains the same...

**Comment by linux-cultist** [comment]
First problem is something I didn't consider actually. I think what probably happens is that the plugin is trying to activate the venv from cache, even when it's deleted, since it's still in the file that keeps track of cached venvs. We should bugfix that, thank you.

It's strange that you don't get any venvs in the telescope viewer though. Where are the poetry venvs on disk?

**Comment by linux-cultist** [comment]
I added a check in the latest commit so the plugin doesnt try to activate a venv that has been deleted. 

So now its a question of where your poetry venvs are and if the plugin should find them. The plugin looks in `~/Library/Caches/pypoetry/virtualenvs` if you are on a Mac for example.

**Comment by metal3d** [comment]
Hi, sorry for the delay.

- I'm on Linux, Fedora 40
- I don't use poetry, as I explained earlier I changed to pipenv and it never find any virtualenv

That worked with poetry (ASAIK), and it work with venv in the project.

**Comment by linux-cultist** [comment]
Ok, thank you. And your pipenv venvs are in default locations?

**Comment by linux-cultist** [comment]
I realized I didnt create default searches for `pipenv` environments in the `regexp` version of the plugin. Clearly an oversight and I will fix that right away...

**Comment by linux-cultist** [comment]
This should be fixed now in the regexp version. Thanks for pointing this out!
