### ISSUE TITLE
venv cached env doesn't trigger on files not named *.py

### ISSUE THREAD

**Issue by singiamtel** [linux-cultist/venv-selector.nvim#159]
I'm using files that don't have the right extension because they're called as scripts, but they have the python shebang ``#!/usr/bin/env python`` so the LSP is starting but the venv is not being activated

Would it be a problem to always run the cached venv on LSP start instead? e.g.

```diff
diff --git a/lua/venv-selector/init.lua b/lua/venv-selector/init.lua
index ba88df1..b087aa1 100644
--- a/lua/venv-selector/init.lua
+++ b/lua/venv-selector/init.lua
@@ -13,7 +13,6 @@ local function on_lsp_attach()
 end
 
 vim.api.nvim_create_autocmd("LspAttach", {
-    pattern = "*.py",
     callback = on_lsp_attach,
 })
 ```

**Comment by kahojyun** [comment]
I encountered a similar issue. When I open a `.pyi` file, the plugin doesn’t automatically load the previously selected venv, so I have to choose it manually.

**Comment by linux-cultist** [comment]
Without any pattern, the plugin would activate on all files, and not just python files. It would send all files you open to the lsp server, trying to activate them.

So I think that will create a lot of weird issues unfortunately.

@kahojyun I guess I should add  `.pyi` file though since it's still python. Havent used that extension myself.

**Comment by singiamtel** [comment]
It could run the autocmd on filetype too, instead of extension

**Comment by linux-cultist** [comment]
@singiamtel I didn't know that, but will look into it then... Thank you.

**Comment by singiamtel** [comment]
> @singiamtel I didn't know that. How will the Linux system know the text file is a python file if it doesn't look at the extension?

I think vim has a few random ways to set a filetype besides extension, like parsing the shebang or comments like ``# vi: ft=python``

**Comment by linux-cultist** [comment]
I looked in the docs for autocmd patterns and I cant seem to find another way of matching besides the extension:

https://neovim.io/doc/user/autocmd.html#_6.-patterns

Maybe you know some way? I understand i can add manual code to try and open every file and look for shebang lines, but that is not a great solution...

**Comment by linux-cultist** [comment]
@kahojyun I added `*.pyi` files as well to the autocommand, so opening such a file should load the cached venv now also.

**Comment by singiamtel** [comment]
@linux-cultist  I was thinking about https://neovim.io/doc/user/autocmd.html#FileType, but I guess you cant't chain it with LspStart this way.

How about something like this instead? (Untested)

```diff
diff --git a/lua/venv-selector/init.lua b/lua/venv-selector/init.lua
index 87c05b9..4e8c5ea 100644
--- a/lua/venv-selector/init.lua
+++ b/lua/venv-selector/init.lua
@@ -6,14 +6,16 @@ local path = require("venv-selector.path")
 local ws = require("venv-selector.workspace")
 
 local function on_lsp_attach()
-    local cache = require("venv-selector.cached_venv")
-    if config.user_settings.options.cached_venv_automatic_activation == true then
-        cache.retrieve()
+	if vim.bo.filetype == 'python' then
+		local cache = require("venv-selector.cached_venv")
+		if config.user_settings.options.cached_venv_automatic_activation == true then
+			cache.retrieve()
+		end
     end
 end
 
 vim.api.nvim_create_autocmd("LspAttach", {
-    pattern = "*.py,*.pyi",
+    pattern = "*",
     callback = on_lsp_attach,
 })
```

**Comment by linux-cultist** [comment]
Its a nice idea. Will test it and see how well it works. :)

**Comment by linux-cultist** [comment]
This works, and I added it in the latest commit. However, vim still doesnt recognize a shell script as a python file even if it has a shebang at the top, so not sure this will help with anything. 

It detects .py and .pyi files just fine though.

**Comment by linux-cultist** [comment]
Very good. Thank you. :)
