### ISSUE TITLE
Venv "doesnt exist". However, it does.

### ISSUE THREAD

**Issue by aryang20** [linux-cultist/venv-selector.nvim#161]
Every time I try to switch to an interpreter, it says it does not exit.

**Comment by linux-cultist** [comment]
Going to need more info than that.. Can you list the venvs on the file system that the plugin thinks doesn't exist? Are they symlinks or ordinary files? Which venvs are detected and which are not?

**Comment by linux-cultist** [comment]
Hi again.

I realized now that you are using the old version of VenvSelect. Its not being updated anymore and a new version has been rewritten from scratch that works in a very different way. Please try that one instead. You have a link to it at the top of the readme.

I think it will work a lot better for you.
