### ISSUE TITLE
changing from telescope to fzf-lua - venv selector not working 

### ISSUE THREAD

**Issue by Trid-collab** [linux-cultist/venv-selector.nvim#162]
I am new to this. I have using venv- selector along with the default python language setting in Lazyvim. I have noticed that when I change file picker from the default  telescope to fzf-lua - venv stops working. Does this need any changes to my setting

**Comment by linux-cultist** [comment]
Hi,

The plugin is only written to work with telescope viewer right now but there is some work in progress to see if we can add fzf-lua support. :)
