### ISSUE TITLE
Naming of venv virtual environments in path

### ISSUE THREAD

**Issue by edevil** [linux-cultist/venv-selector.nvim#163]
I use plain venv virtual environments which I create in the same path, lets call it `/dev/venvs`. Inside this path I name my environments with the name of the project they refer to: `/dev/venvs/project1`...

I have tried setting `path` to this directory, but no venvs are found. From reading the rest of the options it appears that only virtual environments with the name `venv` would be found. Am I correct to assume that my workflow is not currently supported by this plugin?

Thanks.

**Comment by edevil** [comment]
Never mind, just noticed the regexp branch that works perfectly. :)

**Comment by linux-cultist** [comment]
Very good :) Yeah the rewritten regexp version works a lot better.
