### ISSUE TITLE
Make selected venv color a configuration option

### ISSUE THREAD

**Issue by rodhash** [linux-cultist/venv-selector.nvim#167]
Hi

Can we have this HL color be set by our theme? Or let us set it manually?

Even if I set it manually this line seems to override whatever color I define in my own theme/config.

https://github.com/linux-cultist/venv-selector.nvim/blob/c43dc6bf8c7e7cf124a991775ed3defe87112d3a/lua/venv-selector/init.lua#L22

Thanks.

**Comment by linux-cultist** [comment]
I agree, this should be at least configurable with whatever you want. Lets keep this as a feature request and we can add it in some coming update. :)

**Comment by linux-cultist** [comment]
I added the config option `telescope_active_venv_color` in the latest commit, so now you can set the color to something else than green. :)
