### ISSUE TITLE
Lazy eval cwd in venv.lua

### ISSUE THREAD

**Issue by BonaBeavis** [linux-cultist/venv-selector.nvim#17]
https://github.com/linux-cultist/venv-selector.nvim/blob/653b2b37ba5c7637dbc29d2d4f5f236d7e8f93e4/lua/venv-selector/venv.lua#L14

M.cwd is always set to the home directory in my setup. Change M.cwd to:

```lua
	local venv_cache = {
		[vim.fn.getcwd()] = { value = venv.value },
	}
```

**Comment by linux-cultist** [comment]
Just to understand what you would like, do you want your current working directory to be the same as the virtual environment directory?

**Comment by linux-cultist** [comment]
I understand now after looking at the code. This was added in a PR by another developer and I think the intention was to use the current cwd every time the VenvSelectCached is executed. 

Will change it so it always looks at the current cwd.
