### ISSUE TITLE
Quoted strings are parsed incorrectly on windows

### ISSUE THREAD

**Issue by ayooh** [linux-cultist/venv-selector.nvim#171]
As I mentioned in https://github.com/linux-cultist/venv-selector.nvim/pull/169#discussion_r1749911764, there's still a bug here such that the spaces in the path are not resolved.

A simple example:
```lua
"fd.exe python.exe 'C:/space test' --full-path --colora never"
```
output:
```lua
{ "C:\\space test", "fd.exe", "python.exe", "--full-path", "--color", "never" }
```

**Comment by linux-cultist** [comment]
That's so strange. I tested that even. Let me test again tomorrow. Thanks for reporting it!

**Comment by linux-cultist** [comment]
I can confirm there is a bug that happens when using quotes in general - the quoted string end up first in the lua table, which is incorrect of course.

Will have a look tonight.

**Comment by linux-cultist** [comment]
Still not fixed this completely. Quoted strings dont work currently.

**Comment by linux-cultist** [comment]
@ayooh Hopefully fixed now, please test on your system.

This is much trickier than I thought from the start. Splitting strings on space is easy, but not splitting when they are quoted led to a complicated function.
