### ISSUE TITLE
Recent regexp update does not work on windows 

### ISSUE THREAD

**Issue by DaveanandMannie** [linux-cultist/venv-selector.nvim#173]
Hello, its me again on the most recent update of `regexp`  I am facing the issue again where cached dirs work but searching does not.

here is what the logs provide
```
2024-09-13 18:18:59 [DEBUG]: [fd error]: No valid search paths given.
2024-09-13 18:18:59 [INFO]: Searching finished.
2024-09-13 18:18:59 [DEBUG]: Calculating path similarity based on: 'C:\Users\support\Desktop\workspace\test'
2024-09-13 18:18:59 [DEBUG]: Sorting telescope results on path similarity.
2024-09-13 18:19:00 [DEBUG]: Starting 'cwd': 'fd Scripts\python.exe$ C:\Users\support\Desktop\workspace\test --full-path --color never -HI -a -L'
...
2024-09-13 18:18:54 [DEBUG]: [fd error]: regex parse error:
2024-09-13 18:18:54 [DEBUG]:     Scripts\python.exe$
2024-09-13 18:18:54 [DEBUG]:            ^^^
2024-09-13 18:18:54 [DEBUG]: error: Unicode property not found
```

It seems to be finding my `cwd` correctly but when running the `fd Scripts\python.exe$ C:\Users\support\Desktop\workspace\test --full-path --color never -HI -a -L`  directly in my my terminal i get the same parse error. 

When I add another `\` to escape it works:
`fd Scripts\\python.exe$ C:\Users\support\Desktop\workspace\test --full-path --color never -HI -a -L`
........................^
```
PS C:\Users\support\Desktop\workspace\test> fd Scripts\python.exe$ C:\Users\support\Desktop\workspace\test --full-path --color never -HI -a -L
[fd error]: regex parse error:
    Scripts\python.exe$
           ^^^
error: Unicode property not found

Note: You can use the '--fixed-strings' option to search for a literal string instead of a regular expression. Alternatively, you can also use the '--glob' option to match on a glob pattern.
PS C:\Users\support\Desktop\workspace\test> fd Scripts\\python.exe$ C:\Users\support\Desktop\workspace\test --full-path --color never -HI -a -L
C:\Users\support\Desktop\workspace\test\.venv\Scripts\python.exe
PS C:\Users\support\Desktop\workspace\test>
```
configuration: 
```
  {
    "linux-cultist/venv-selector.nvim",
    -- branch = "windows_lua_table",
    branch = "regexp",
    cmd = "VenvSelect",
    enabled = function()
      return LazyVim.has("telescope.nvim")
    end,
    opts = {
      settings = {
        options = {
          notify_user_on_venv_activation = true,
        },
      },
    },
```
Not sure if this helps. For now I will switch over to a previous commit / the windows_lua_table branch in the mean time.

**Comment by linux-cultist** [comment]
Ok thank you. I just recently pushed an update to make windows searching independent of the shell and avoiding the need to escape things, but you may have ran into a bug here. 

Can you try using forward slashes ('/' ) instead in the path and the regexp? See if that works in the command line and in the plugin?

**Comment by DaveanandMannie** [comment]
> Can you try using forward slashes ('/' ) instead in the path and the regexp? See if that works in the command line and in the plugin?

I tried these 
```
PS C:\Users\support\Desktop\workspace\test> fd Scripts/python.exe$ C:\Users\support\Desktop\workspace\test --full-path --color never -HI -a -L
PS C:\Users\support\Desktop\workspace\test> fd Scripts/python.exe$ C:/Users/support/Desktop/workspace/test --full-path --color never -HI -a -L
PS C:\Users\support\Desktop\workspace\test> fd Scripts/python.exe$ C:/Users/support/Desktop/workspace/test/ --full-path --color never -HI -a -L
PS C:\Users\support\Desktop\workspace\test> fd Scripts\\python.exe$ C:\Users\support\Desktop\workspace\test --full-path --color never -HI -a -L
C:\Users\support\Desktop\workspace\test\.venv\Scripts\python.exe
PS C:\Users\support\Desktop\workspace\test>
```
In the command line only the last one returned the correct path

In the plugin I tried
```
{
    "linux-cultist/venv-selector.nvim",
    -- branch = "windows_lua_table",
    branch = "regexp",
    cmd = "VenvSelect",
    enabled = function()
      return LazyVim.has("telescope.nvim")
    end,
    opts = {
      settings = {
        search = {
          my_venvs = {
            command = 'fd Scripts//python.exe$ --full-path --color never -HI -a -L'
          }
        },
        options = {
          debug = true,
          notify_user_on_venv_activation = true,
        },
      },
    },
    ft = "python",
    keys = { { "<leader>cv", "<cmd>:VenvSelect<cr>", desc = "Select VirtualEnv", ft = "python" } },
  },

```
This one worked but
`fd Scripts/python.exe$ --full-path --color never -HI -a -L`
`fd Scripts\python.exe$ --full-path --color never -HI -a -L`
fd Scripts\\python.exe$ --full-path --color never -HI -a -L`
didn't work

**Comment by linux-cultist** [comment]
After experimenting a bit with this again in Windows Powershell and CMD:

```
- this works in fd
fd Scripts\\python.exe $HOME/workspace --full-path 

- this works in VenvSelect
fd Scripts//python.exe $HOME/workspace --full-path 
```

So by switching the double slashes in the regexp expression around when you put it into VenvSelect, things should work.

I was trying this morning to see if I could do this automatically in code, but didnt succeed. Since '\' is an escape character in lua, its easiest to just avoid using it.

So please change your search to use this approach and things should work. Let me know how it goes!

**Comment by DaveanandMannie** [comment]
Yeah explicitly setting the search does work.  Thanks again for all your help. 
For now 
```
        search = {
          cwd = { command = "$FD Scripts//python.exe$ $CWD --full-path --color never -HI -a -L" },
        },
```
As I encounter related issues I'll define more searches 
I understand the headache with escape chars. Spun my wheels for hours with Python scripts for work between network drives in the Windows cmd at work.

It's worth mentioning the plugin is great. I often work between many projects with multiple venvs, which saves quite a bit of time. It is also a huge help in cases where ~I totally never forget to~ deactivate/switch venvs. I could imagine the number hours saved is non-trivial 😂

**Comment by linux-cultist** [comment]
Yeah it's a huge pain point with escape chars, specially when trying to run shell commands and have them work on all platforms. But I pray to god it's fixed now and will "just work".

I will add some section in the Readme about how windows users need to switch the slashes when putting the regexp in the plugin settings.

And thanks for the kind words about the plugin! It's why I wrote it, because I didn't like having to leave neovim just to change a venv. None of the other editors require this, so I wanted to make it work with neovim too.

I will close this issue then :) See you around!
