### ISSUE TITLE
Venv search gets killed with timeout on network directory

### ISSUE THREAD

**Issue by KerekesDavid** [linux-cultist/venv-selector.nvim#175]
I'm trying to select a venv for a project that's inside an sftp remote directory. The vnenv itself is under `../miniforge3/envs/vnev`. I get the following errors:

```
   Error  11:23:05 notify.error VenvSelect Search with name 'workspace' took more than 5 seconds and was stopped. Avoid using VenvSelect in your $HOME directory since it searches all hidden files by default.
   Error  11:23:05 notify.error VenvSelect Search with name 'cwd' took more than 5 seconds and was stopped. Avoid using VenvSelect in your $HOME directory since it searches all hidden files by default.
```

The search is very much expected to take more than 5 seconds.

It would be nice to have a way to control the timeout so this doesn't happen. Currently I can't see a config for this, please point me towards one if it exists :)

What could also help if I could give VenvSelect an explicit directory to search for venvs, such as `:VenvSelect ../miniforge3/envs/` so it doesn't have to crawl a 1PB network drive.

**Comment by linux-cultist** [comment]
Hi,

There is an option for the timeout: `search_timeout = 5` (set it to something else)

And you can turn off the default searches with `enable_default_searches = false` and then add your own search in a specific directory:
```
    require("venv-selector").setup {
        settings = {
          search = {
            network_drive_venvs = {
              command = "fd python$ /your_network_drive/path --full-path",
            },
          },
        },
      }
```

**Comment by KerekesDavid** [comment]
Ah sorry about missing the config, I'm new to neovim :)

I checked in the [configuration-options](https://github.com/linux-cultist/venv-selector.nvim?tab=readme-ov-file#configuration-options) part of the readme, and in [config.lua](https://github.com/linux-cultist/venv-selector.nvim/blob/main/lua/venv-selector/config.lua).

Is there a usual spot for this kinda stuff where I should have looked, or does it just happen to be undocumented?

**Comment by linux-cultist** [comment]
It's in the Readme for the regexp branch, so if you switch to that one in github, there is a lot of info about the plugin. It has many options. :)

**Comment by KerekesDavid** [comment]
Ah, I also see the support for in-situ custom searches such as `:VenvSelect fd 'python$' . --full-path -IH -a`, that's great!

I guess this issue was more about not finding that the regexp branch was the actual main branch. (Which is the branch that lazyvim set up for me in the first place.) Thanks for the help!

**Comment by linux-cultist** [comment]
Yeah it's because I did a full rewrite to support your own searches and I wanted to keep the main branch around for a while to not force users to upgrade.

It's a bit confusing right now, but I'm thinking in a few more months, we point the main branch to the regexp branch and remove the old code. Just wanted to keep it around not to force users to change their config until it's stable and used by a lot of people.

Enjoy the plugin and neovim :)
