### ISSUE TITLE
DAP-UI is not using the selected environment

### ISSUE THREAD

**Issue by DWarez** [linux-cultist/venv-selector.nvim#178]
Hello,
it seems that when using [dap-ui](https://github.com/rcarriga/nvim-dap-ui) the selected venv is not used.

Example:

![image](https://github.com/user-attachments/assets/8ea3244e-d64c-4f0f-99eb-fd86ac668e34)

This is my configuration:

```
return {
  "linux-cultist/venv-selector.nvim",
  dependencies = {
    "neovim/nvim-lspconfig",
    "mfussenegger/nvim-dap",
    "mfussenegger/nvim-dap-python", --optional
    { "nvim-telescope/telescope.nvim", branch = "0.1.x", dependencies = { "nvim-lua/plenary.nvim" } },
  },
  lazy = false,
  branch = "regexp", -- This is the regexp branch, use this for the new version
  config = function() require("venv-selector").setup() end,
  keys = {
    { ",v", "<cmd>VenvSelect<cr>" },
  },
}
```

Is integration with dap-ui not supported?

**Comment by linux-cultist** [comment]
No, I never tested the plugin with `dap-ui`. Is there some special way to set a python environment for `dap-ui` to use? Sorry, i dont know much about it. But someone who uses this would probably be able to see if `VenvSelect` can support it easily.

**Comment by DWarez** [comment]
> No, I never tested the plugin with `dap-ui`. Is there some special way to set a python environment for `dap-ui` to use? Sorry, i dont know much about it. But someone who uses this would probably be able to see if `VenvSelect` can support it easily.

Thanks  for the reply :smile: 
In case someone is facing the same problem, a workaround is to select the venv via the `nvim-dap` configuration, as follows:

```
local dap = require "dap"
dap.configurations.python = {
  {
    -- The first three options are required by nvim-dap
    type = "python", -- the type here established the link to the adapter definition: `dap.adapters.python`
    request = "launch",
    name = "Launch file",
    -- Options below are for debugpy, see https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings for supported options

    program = "${file}", -- This configuration will launch the current file if used.
    pythonPath = function()
      -- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
      -- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
      -- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
      local cwd = vim.fn.getcwd()
      if vim.fn.executable(cwd .. "/venv/bin/python") == 1 then
        return cwd .. "/venv/bin/python"
      elseif vim.fn.executable(cwd .. "/.venv/bin/python") == 1 then
        return cwd .. "/.venv/bin/python"
      else
        return "/usr/bin/python"
      end
    end,
  },
}
```

**Comment by linux-cultist** [comment]
Ok great! I will add it to the `README.md`. Actually thinking of restructuring it a bit also while im at it.... :)

Then we close this for now, and if someone has ideas how to support it without a workaround, we could implement it. I just dont know enough about it myself. :)
