### ISSUE TITLE
Silence the `Activated` message

### ISSUE THREAD

**Issue by petobens** [linux-cultist/venv-selector.nvim#23]
I use the statusline to indicate whether I have an active enviroment or not.
I was wondering  whether you could make optional the `Activation` message in https://github.com/linux-cultist/venv-selector.nvim/blob/479a145f8f4dd854cffd7289f18b8267f82e5cf0/lua/venv-selector/venv.lua#L93

**Comment by linux-cultist** [comment]
Yes absolutely. I can add it this weekend, but you can also make a PR yourself if you have time before that. Some option that is true by default would probably be easiest to understand for users, and you can set it to false to not get notified.

If you don't have time I will add it on Saturday. :)

**Comment by petobens** [comment]
Hi @linux-cultist ; I'd probably wait for you to add it since I understood per https://github.com/linux-cultist/venv-selector.nvim/issues/21#issuecomment-1529115354 that you are also going to do some refactoring..

Thanks :)

**Comment by linux-cultist** [comment]
Yeah I want to, but have been very busy now with a new job and lots of stuff to learn there. But I hope I can do some refactoring and cleanup next weekend. But adding that flag is quick and i will do that today. :)

**Comment by linux-cultist** [comment]
Ok, I added the option `notify_user_on_activate` that you can set to false, and the plugin will not say anything on venv activation. :)

**Comment by petobens** [comment]
Great thanks!
