### ISSUE TITLE
After selecting virtual env neovim doesn't refresh

### ISSUE THREAD

**Issue by Souravpakhira** [linux-cultist/venv-selector.nvim#24]
After selecting virtual env from the listing my neovim doesn't refresh itself. Im using astrovim and my system is Ubuntu.

**Comment by linux-cultist** [comment]
Ah ok. I dont use astrovim so not sure what could be causing it. When you say neovim doesnt refresh itself, you mean you get the listing of virtual environments, but selecting one doesnt make it active?

**Comment by Souravpakhira** [comment]
Im closing this issue. Its the issue of pylint what i get now. When selecting from list virtual env gets activated but the linting errors doesn't go away.

**Comment by linux-cultist** [comment]
Thank you!
