### ISSUE TITLE
Suggestion: better way to refresh telescope

### ISSUE THREAD

**Issue by yolong-lin** [linux-cultist/venv-selector.nvim#46]
The border of the telescope will flash whenever refreshing venv.

It seems that you create a new picker instead of refresh the current one.

If the purpose of flashing is the refresh animation, then I think it might be more appropriate to clear the results first and then fill in the new results.

**Comment by linux-cultist** [comment]
Great suggestion. It doesnt flash for me so I didnt notice that, but I will see if I can refresh the current one instead. :+1:

**Comment by yolong-lin** [comment]
It seems that only happen in tmux.

**Comment by linux-cultist** [comment]
Yeah ok. 

I messed around a bit with trying to only refresh the viewer but couldnt easily get it to work without being buggy. There is probably a way if you know the telescope code well.

My attempts were to use a variable (M.created) to keep track of if the viewer had been created already, and then try to do something else if it had. But Im getting errors when trying this and im not sure if this is how telescope is supposed to be used either. Im lacking some good docs for stuff like this.

```
	if M.created == nil then
		M.created = M.pickers.new({}, opts)
		M.created:find()
	else
		M.created:refresh_previewer()
	end

```

Getting this to work may help with flashing in tmux but not sure. If other telegram pickers in other plugins are not flashing, then probably there is a way to do it that tmux will like more.

**Comment by yolong-lin** [comment]
Oh, I', sorry. This is unrelated to tmux.

**Comment by linux-cultist** [comment]
Thanks for contributing a solution to this. Closing the issue.
