### ISSUE TITLE
fd command not working in Ubuntu distro

### ISSUE THREAD

**Issue by Stewart86** [linux-cultist/venv-selector.nvim#6]
## Context

OS: Windows 11 running WSL2 Ubuntu 22.04
Default Shell set with `chsh`: Fish
Neovim version: 0.8
Plugin manager: Lazy
Configuration used:  according to README.md guide for `Lazy`
requirements installed: 
fd: yes (using `apt install fd-find`)
telescope: yes

## Expected behaviour

Using mapped key (\<leader\>vs) should show telescope with a list of virtualenvs to pick from.

## Actual behvaiour

after keying `<leader>vs` nothing happened.

## Investigate

After some debugging, realised that `vim.loop.spawn()` is using the `sh` shell to execute the `fd` command. As I am using Ubuntu, according to fd guide there is a conflict with another binary in the distro, so alias was suggested to be use. As a result, I have set alias for bash shell and fish shell. But `vime.loop.spwan()` is not using either one. 

turn out I changed the command from `fd` to `fdfind` and it works as expected.

## Proposal

Allow a config variable to change `fd` to `fdfind` or `find` depends on user preference.

**Comment by linux-cultist** [comment]
Ah thank you for taking the time to understand the problem and suggest a good fix. :)  Had no idea about this being the case on Ubuntu. I will add a quick option for setting the fd variable to some other name.

**Comment by linux-cultist** [comment]
If you update the plugin now, you can set the option "fd_binary_name" to the name of fd you have on your system. I added it to the README also but as an example:

```
require("venv-selector").setup({
    fd_binary_name = "fd_find"
})
```

**Comment by linux-cultist** [comment]
Hopefully this solution works for you - it should! Otherwise feel free to reopen the issue. Thank you for reporting this!

**Comment by Stewart86** [comment]
Yes! Perfect! it works now. Thanks for being so quick to fix this. Except, there are a couple of improvement I could also suggest. If i have time later today, I might raise a PR for it. Or if you got around to it, that would be great!

1. expose a venv name for statusline display so we know which python interpreter we are using any time by looking at the statusline. Maybe something like `venv_name = (poetry) my_project_2j8w2a23`

2. instead of printing use notify API to notify the activation of the venv

3. when a venv is set, remember the setting, so the next time vim is loaded, it will default to that saved venv instead of needing to activate again manually

**Comment by linux-cultist** [comment]
Thanks for the kind words! :)

For number one, there are two functions you can call. I added them yesterday so they are new, but there is info on the readme.

Number 2 - yes I've been thinking this also. You mean the notify plugin right? I could try to load that one and use it if it exists. I don't like the printing very much either and would prefer a better way. 

Number 3 - This could easily be implemented and put behind an option. Maybe even better if it's tied to a specific workspace, so it would remember per workspace?

**Comment by linux-cultist** [comment]
1. Both the path of the venv folder and the path to the python can be retrived by calling these functions:

require("venv-selector").get_active_path() -- Gives path to the python executable inside the activated virtual environment
require("venv-selector").get_active_venv() -- Gives path to the activated virtual environment folder

I think its better to give the user the path without any formatting, and then allow the user to format the information how he/she wants in the statusbar. If we add ("poetry") here in the output, users who dont want that will have to try and scrub that information away, and also the function wont work with other plugins that just expects a path. :)

So for your use case - call these functions from your statusbar, and then format the output how you want it to look. :) There are vim functions for shortening a path for example that you can use in your status bar code.

2. Cool, didnt actually know this. I guess also if we use vim.notify, then if someone has the nvim notify plugin, it will automatically use the plugin. So yeah, lets use vim.notify to show the "venv activated" message.

3. Interesting... its necessary to add pythonPath for ordinary venvs to be activated by the plugin. I think with your config above, lspconfig would always pick the root dir whre it finds a git folder or a pyproject.toml folder, so it doesnt really care what you pick with VenvSelect. But I could be wrong, need to do more testing on this for sure. :)

**Comment by Stewart86** [comment]
1. got it. You have a point. 
2. I have made a PR for this
3. I did some experiment, but removing the root dir my code works fine too with `M.set_pythonpath(venv_python)` commented out. I also checked `lspconfig` repo on pyright portion. it did not mentioned anything about `before_init` like what you did in your code. Maybe I just don't have much in depth knowledge on the lsp side of things.

**Comment by linux-cultist** [comment]
I'm also not that knowledgeable about the lsp stuff, need to investigate more going forward. :)

**Comment by nikolaevigor** [comment]
> Allow a config variable to change fd to fdfind or find depends on user preference.

May I suggest to add some indication if fd binary not found. Also have `fdfind` instead of `fd`, and it took me some debugging to understand why nothing happens on `:VenvSelect`. So some message with error would be great

**Comment by linux-cultist** [comment]
Yes you are correct :) There is an issue for this already and I wanted to detect if fdfind is available on the system and use that one if it is. And otherwise throw an error message.
