### ISSUE TITLE
How to active the python environment?

### ISSUE THREAD

**Issue by cxzhou35** [linux-cultist/venv-selector.nvim#65]
Hi author,
Thank you for this wonderful plugin, which helps me a lot, but I meet some problems here.
When I trigger the `VenvSelect` command with the defined keymap, the envs menu will popup, all this is working properly.

<img width="1323" alt="image" src="https://github.com/linux-cultist/venv-selector.nvim/assets/80182956/28329994-46f1-405d-8c47-485541ff9fa3">

But when I choose one of the conda env with the `<CR>` keymap, it will jump to the envs folder without activing the chosen envs, how to fix that?

I am using lazyvim as my config, here is the config related to this plugin.

```lua
return {
  "linux-cultist/venv-selector.nvim",
  cmd = "VenvSelect",
  dependencies = { "neovim/nvim-lspconfig", "nvim-telescope/telescope.nvim" },
  event = "VeryLazy",
  opts = {
    search = false,
    name = {
      "venv",
      ".venv",
      "env",
      "envs",
      ".env",
    },
    anaconda_base_path = "/Users/vercent/miniconda3",
    anaconda_envs_path = "/Users/vercent/miniconda3/envs",
  },
  keys = { { "<leader>cv", "<cmd>:VenvSelect<cr>", desc = "Select VirtualEnv" } },
}
```

**Comment by linux-cultist** [comment]
Hi and thank you!

It should activate the venv so not sure what is going on. Can you add "enable_debug_output = true"  to your VenvSelect options and restart neovim? Then when you use the plugin, you will get lots of messages and you can see all of them if you type :messages in neovim. Share the output here and we will maybe see what's going on. Thank you!

**Comment by cxzhou35** [comment]
Thank you for your quick reply, I have tried what you suggest, here is the message:
![image](https://github.com/linux-cultist/venv-selector.nvim/assets/80182956/efc85461-3126-48b2-bccc-865b2796c5c8)

And more, I found that this case happened when I choose the first env without typing anything into the input box, if I type some input texts then choose one of the result, this plugin works as well. I can't read something related to this case according to the message :(

**Comment by linux-cultist** [comment]
Thank you for the picture, but I dont see anything strange going on from that... 

Can you install https://asciinema.org/ and make a short video showing the problem? And make sure to not include any personal information in the video.

**Comment by linux-cultist** [comment]
Closing this because of no response, but please open if you think there is an issue. :)

**Comment by SerMeliodas** [comment]
I have the same issue.
![nv](https://github.com/linux-cultist/venv-selector.nvim/assets/53590450/ee2bb2d1-4ff3-4de9-9eb2-b2743c812c72)

**Comment by SerMeliodas** [comment]
> Closing this because of no response, but please open if you think there is an issue. :)

I have the same issue.

![nv](https://github.com/linux-cultist/venv-selector.nvim/assets/53590450/57bbb902-65d6-4973-995a-d44779ab051c)

**Comment by bartopine** [comment]
Hello! .. i have the same issue also .. when i select a virtual environment from the list .. it goes to the directory explorer showing the selected .venv folder contents.

**Comment by SerMeliodas** [comment]
> Hello! .. i have the same issue also .. when i select a virtual environment from the list .. instead of activating the venv .. it goes to the directory explorer showing the selected venv folder contents.
> 
> 
> 
> Found the solution .. when confirming using <cr> in normal mode .. it will go to the file explorer .. when confirming in insert mode .. it activates the venv.. @SerMeliodas 

Thanks, i'll try it.

**Comment by KonstantinosTsitoumis** [comment]
> Hello! .. i have the same issue also .. when i select a virtual environment from the list .. instead of activating the venv .. it goes to the directory explorer showing the selected venv folder contents.
> 
> Found the solution .. when confirming using in normal mode .. it will go to the file explorer .. when confirming in insert mode .. it activates the venv.. @SerMeliodas

worked!
