### ISSUE TITLE
Miniconda support? (python.exe in venv root directory, not scripts or bin)

### ISSUE THREAD

**Issue by xaviernogueira** [linux-cultist/venv-selector.nvim#66]
First off thanks for a sweet plugin!

That said, I was trying to use it with a mini-conda environment and ran into an issue where my `python.exe` executables are housed in the root venv directory.

For example:
`.../Miniconda3/envs/my_env_name/python.exe`

The `anaconda { python_parent_dir = nil }` option only let's one pick `/Scripts` or `/bin`, neither of which apply in a Miniconda case. The default is `Scripts` as I'm sure your aware.

Any chance you can create an option like anaconda { python_parent_dir = 'root' }?

I am a lua beginner, but I may give it a shot if I can figure it out.

Thanks!

**Comment by xaviernogueira** [comment]
Nevermind, realized I can pass in a blank string.

**Comment by linux-cultist** [comment]
Yes, and I should document that better. :) Thanks for reminding me and enjoy the plugin!
