### ISSUE TITLE
Doesn't detect venv

### ISSUE THREAD

**Issue by jo-project** [linux-cultist/venv-selector.nvim#68]
Hi author,
I am using WSL and try to use this plugin, but it won't detect my virtual environment (venv)

Do you know how to fix it? Thank you!

![venv_doesnt_found](https://github.com/linux-cultist/venv-selector.nvim/assets/122333339/608293f5-6ead-4ec9-a468-f513a7be6498)
![Venv_Config](https://github.com/linux-cultist/venv-selector.nvim/assets/122333339/36e1c92b-a898-467f-a2c9-3910b3839b9d)

**Comment by linux-cultist** [comment]
Hi,

I dont know much about WSL but I guess it should work there. Do you have `fd` installed in there?

You can add `enable_debug_output = true` in your setup function there also, and next time you restart neovim you should get lots of debug output from VenvSelect. Type ':messages` in neovim to see all of them. And then post it here. Lets see what its trying to do.

**Comment by linux-cultist** [comment]
Got anything interesting in the debug output?

**Comment by jo-project** [comment]
Now it works, but can I ask, how to make the Menu only contains venv of the current directory or parent (one path above current dir), I dont want to show anything else. Is there a way to make that happen? Thank you!

**Comment by linux-cultist** [comment]
Yeah if you set parents to 0, it will only look in your current directory and not search parent directory. And you can disable searching for venv manager venvs also, check the Readme. :)

**Comment by linux-cultist** [comment]
Did you get it to work? :)

**Comment by linux-cultist** [comment]
Closing the issue as solved.
