### ISSUE TITLE
`search = false` not returning valid results

### ISSUE THREAD

**Issue by patrickarmengol** [linux-cultist/venv-selector.nvim#7]
The configuration examples note the following about the *search* configuration option:

> If you only use venvs located in project folders, you can set search = false and search_workspace = true.

and

> You can set this to false to speed up the plugin if your virtual envs are in your workspace, or in Poetry or Pipenv locations. No need to search if you know where they will be.

Yet, the following configuration returns no results:
```lua
  {
    "linux-cultist/venv-selector.nvim",
    opts = {
      search_venv_managers = false,
      search_workspace = true,
      search = false,
      name = ".venv",
    },
  },
```

If I set search to true, the results appear, but are not exclusive to the workspace anymore.

**Comment by linux-cultist** [comment]
Thank you for taking the time to report this. Lets see what your lsp server reports as a workspace. If you run this command in vim command mode (press colon):
`
lua =vim.lsp.buf.list_workspace_folders()
`

Do you get the path to your project folder? You can also run `LspInfo` and see what it says as "root directory" in that dialog box.

**Comment by patrickarmengol** [comment]
Aww man, I really should have checked if I was on the latest version...
Looks like some recent changes to the plugin have fixed this issue. Sorry for the trouble. I'll check on the other issues I opened as well. 

Anyway, thanks for the quick reply.

**Comment by linux-cultist** [comment]
Thank you, and enjoy the plugin! 

I know previous versions had bugs and I think you just noticed a few of them. :) I did a big rewrite of the plugin a few days ago and I think it resulted in a lot more stable code. But please report if you find other weirdness. :)
