### ISSUE TITLE
[feature] Add support for pipx

### ISSUE THREAD

**Issue by fschoenm** [linux-cultist/venv-selector.nvim#72]
Could you please add support for _pipx_ as additional package manager?

_pipx_ stores its virtual environments at  ~/.local/share/pipx/venvs/PACKAGE by default (see https://github.com/pypa/pipx/blob/ac647404902c46019c4cf2da46dc225c5404d986/docs/how-pipx-works.md), as far as I know on each platform.

**Comment by linux-cultist** [comment]
This should be very simple to do in the new version of the plugin I'm working on in the `regexp` branch. You can also add it yourself there if you write a fd command that will pick them up. It's still under heavy development but just wanted to let you know if you want to try it out.

**Comment by linux-cultist** [comment]
Pipx support has been added now to the `regexp` version of the plugin, and its ready for general use now. Try it out. :)
