### ISSUE TITLE
Can not find conda envs enviroment

### ISSUE THREAD

**Issue by ChengAoShen** [linux-cultist/venv-selector.nvim#78]
This is the part of my neovim config about this plugins
```lua
        {"linux-cultist/venv-selector.nvim",
            dependencies = { "neovim/nvim-lspconfig", "nvim-telescope/telescope.nvim", 
                            "mfussenegger/nvim-dap-python","nvim-lua/plenary.nvim" },
            config = function()
                require("venv-selector").setup({
                    fd_binary_name = "find",
                    anaconda_base_path = "/opt/homebrew/Caskroom/miniconda/base",
                    anaconda_envs_path = "/opt/homebrew/Caskroom/miniconda/base/envs",
    
                })
            end,
            event = "VeryLazy", -- Optional: needed only if you want to type `: VenvSelect` without a keymapping
            keys = {{ "<leader>vs", "<cmd>VenvSelect<cr>" },}
        },
```
And this is my conda env list
<img width="878" alt="image" src="https://github.com/linux-cultist/venv-selector.nvim/assets/68673559/cce49370-f465-48bb-b792-4e98839b947e">

However, this plugin can not find the environment as follows.
<img width="1310" alt="image" src="https://github.com/linux-cultist/venv-selector.nvim/assets/68673559/dd35d47a-e532-41ac-93db-0920ea3b63f0">
I'm looking for your reply! Thank you, sir.

**Comment by linux-cultist** [comment]
Hi,

Thanks for making a Github issue! I can look at this the coming weekend. It's been so much stuff going on right now so my time and energy is a bit limited. :)

**Comment by ChengAoShen** [comment]
Great, I'm looking for your reply. Thanks again for expressing my gratitude.

**Comment by ChengAoShen** [comment]
Hi sir, I'm still waiting for your reply! I really desire to use your plugins.

**Comment by linux-cultist** [comment]
Hi,

Thank you for the reminder. :) I also noticed now that you have put "find" as fd_binary_name, and that will not work unless you have replaced the find command with fd on your system? Normally when you install fd, it's called fd or fdfind or similar.

**Comment by ChengAoShen** [comment]
Hi, thanks for your kind help, I forgot to install the `fd` command on my Mac, I originally thought that `find` could work similarly to the `fd` command.
Now, I install `fd`, and the plugin works well, thanks again for you, sir.

**Comment by linux-cultist** [comment]
Great, enjoy the plugin :)
