### ISSUE TITLE
Cannot find correct Python execution path under Miniconda with empty string for anaconda python_parent_dir 

### ISSUE THREAD

**Issue by LeihanChen** [linux-cultist/venv-selector.nvim#79]
Hi,

Thank you for sharing such a great and convenient plugin for us. Unfortunately I had difficulty to use it correctly under my Ubuntu 20.04 and miniconda. Here is my configuration in LazyVim:
```lua
return {
  "linux-cultist/venv-selector.nvim",
  dependencies = { "neovim/nvim-lspconfig", "nvim-telescope/telescope.nvim", "mfussenegger/nvim-dap-python" },
  opt = {
    enable_debug_output = true,
    dap_enabled = true, -- Enable DAP integration.
    anaconda = { python_parent_dir = "" },
    anaconda_base_path = "~/miniconda3",
    anaconda_envs_paths = "~/miniconda3/envs",
    search = false,
  },
  keys = {
    -- Keymap to open VenvSelector to pick a venv.
    { "<leader>vs", "<cmd>VenvSelect<cr>" },
    -- Keymap to retrieve the venv from a cache (the one previously used for the same project directory).
    { "<leader>vc", "<cmd>VenvSelectCached<cr>" },
  },
}
``` 
However, the miniconda paths that venv-selector found is incorrect, which is shown in following screenshots:
<img width="595" alt="venu-selector" src="https://github.com/linux-cultist/venv-selector.nvim/assets/19209592/b6f10aeb-e86f-4e46-8162-182d20ef98ca">
<img width="631" alt="屏幕截图 2023-11-23 180138" src="https://github.com/linux-cultist/venv-selector.nvim/assets/19209592/f7fdc59e-ef71-456e-864d-7cd7da40085c">

The real python interpreter path should be inside `.../Miniconda3/envs/my_env_name/python.exe`, even although I already set `anaconda = { python_parent_dir = "" }` but i do not understand why there is still extra folder path `/lib/python3.7/venv` after ` anaconda_envs_paths`.  Meanwhile I also set `enable_debug_output = true,` to print debug info. Unfortunately when I type `:messages' still I cannot find any debug info. Is there anything incorrect for my setting? 

Sorry for my configuration question as a new Lua and Neovim user.

Best,
Leihan

**Comment by linux-cultist** [comment]
Thank you @mennohofste. I had planned to start to look at this issue but I have managed to attract a really bad man cold over here, so haven't been at my computer for a week or so.

Hopefully your solution fixes the issue.

**Comment by LeihanChen** [comment]
@mennohofste Thank you for the instructions with details for me to understand my issues. Perfectly work.

@linux-cultist Hopefully you recovers fully. Again, really appreciate your plugin and support. Will close this issue.
