### ISSUE TITLE
Setting multiple `name`s returns too many results

### ISSUE THREAD

**Issue by patrickarmengol** [linux-cultist/venv-selector.nvim#8]
The configuration examples note the following about the `name` configuration option:

> NOTE: You can also use a lua table here for multiple names: {"venv", ".venv"}`

When using the following settings, the result set in the telescope window includes all files/dirs in the current directory:

```lua
  {
    "linux-cultist/venv-selector.nvim",
    opts = {
      search_venv_managers = false,
      search_workspace = true,
      search = true,
      name = { "venv", ".venv" },
    },
  },
```

**Comment by linux-cultist** [comment]
Thanks for taking the time to report this. This was very interesting. I cant replicate this but that was not surprising. Which operating system are you using?

**Comment by patrickarmengol** [comment]
No longer an issue in the most recent version.
