### ISSUE TITLE
Use formatting standard for code contributions

### ISSUE THREAD

**Issue by mennohofste** [linux-cultist/venv-selector.nvim#82]
I noticed the project has many different indenting styles, and manually indenting/formatting is no fun. 

@linux-cultist, How do you feel about adding a `.stylua.toml` file to make it uniform and easier to work on? Do you have a personal preference that you could add that to the project? 

I do not mind any style (or care about tabs vs. spaces), however, I think sticking to one is always nicer to work with. If you have no preference, I think copying a config from the official NeoVim project would probably be safest. The closest project is probably [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/.stylua.toml).

What do you think about this?

**Comment by linux-cultist** [comment]
Absolutely, let's do that. I also don't care which formatting as long as it's the same everywhere. Copying lspconfig sounds good to me. Go ahead. :)

**Comment by mennohofste** [comment]
Thanks for the plugin! It is a lifesaver to manage all my venvs.

**Comment by linux-cultist** [comment]
Yeah I had the same use case when I stayed writing this plugin. I just couldn't understand why people wanted to open and close neovim every time they switched a venv, so I wrote this plugin. It didn't get much attention at all at first but slowly got more and more users, and I'm very happy to see it included in Lazyvim too. :)
