### ISSUE TITLE
Struggle With Hooks configuration 

### ISSUE THREAD

**Issue by febridev** [linux-cultist/venv-selector.nvim#88]
on this hooks configuration that is optional or mandatory? because after switch vitrual env :VenvSelect my library still suggest error doesn't import 
<img width="1300" alt="image" src="https://github.com/linux-cultist/venv-selector.nvim/assets/1490986/1437773f-1613-443c-b688-eb021eb3f362">

**Comment by mennohofste** [comment]
If you are using `Pyright`, `Pylance`, or `pylsp`, it should work out of the box. What error are you getting? What venv manager are you using?

**Comment by febridev** [comment]
after choose the venv I didn't get anything 
and library already install on venv still got error on current python file

**Comment by mennohofste** [comment]
What venv manager are you using?

What is your config?

**Comment by linux-cultist** [comment]
@febridev, can you provide the info @mennohofste asked for?

**Comment by febridev** [comment]
this my config 
```local venv_status, venv_selector = pcall(require, "venv-selector")
if not venv_status then
        return
end

venv_selector.setup({
        dependencies = { "neovim/nvim-lspconfig", "nvim-telescope/telescope.nvim", "mfussenegger/nvim-dap-python" },
        event = "VeryLazy",
})
venv_selector.get_active_path()
venv_selector.get_active_venv()
venv_selector.retrieve_from_cache()
```

**Comment by mennohofste** [comment]
`pip` is a package manager, not a venv manager. How do you create virtual environments? What command do you run?

Furthermore, it seems you are using lazy.nvim; however, you are not calling the setup function correctly. The `setup` function of `venv-selector` does not have `dependencies`, nor `event` keys.

I think it is easiest if you read the README thoroughly, as well as the [lazy.nvim](https://github.com/folke/lazy.nvim) documentation.

For reference, this is what a lazy.nvim configuration should look like:
```lua
return {
  'linux-cultist/venv-selector.nvim',
  dependencies = { 'neovim/nvim-lspconfig', 'nvim-telescope/telescope.nvim', 'mfussenegger/nvim-dap-python' },
  config = function()
    require('venv-selector').setup {
      -- Your options go here
      -- name = "venv",
      -- auto_refresh = false
    }
  end,
  event = 'VeryLazy', -- Optional: needed only if you want to type `:VenvSelect` without a keymapping
  keys = {
    -- Keymap to open VenvSelector to pick a venv.
    { '<leader>vs', '<cmd>VenvSelect<cr>' },
    -- Keymap to retrieve the venv from a cache (the one previously used for the same project directory).
    { '<leader>vc', '<cmd>VenvSelectCached<cr>' },
  },
}
```

**Comment by febridev** [comment]
I using this command for create virtual env 
`virtualenv my-env`
and for nvim I use .lua file

**Comment by febridev** [comment]
this issue already solved 
I reset my configuration on neovim + packer
