### ISSUE TITLE
Use pyrightconfig.json if it's in the project root

### ISSUE THREAD

**Issue by kuator** [linux-cultist/venv-selector.nvim#90]
Pyright and Pylance have a `pyrightconfig.json` which can be used to determine venv location. Sample `pyrightconfig.json`
```
{
  "venvPath": "/home/doka/.local/share/virtualenvs",
  "venv": "c142fad17f39dbb53c07810005e5f4eaaf81369e"
}
```

**Comment by kuator** [comment]
> Yes, but this plugin is for switching between venvs dynamically. But maybe you are suggesting that the plugin would pick up whatever is in `pyrightconfig.json` if its in the current working directory?

Yes

**Comment by linux-cultist** [comment]
I went for a slightly different solution here, but one that i think works equally well.

VenvSelect in the `regexp` branch remembers what python you have picked for each working directory, and activates it automatically the next time you open a python file in that directory. 

If you want to give it a try, here is some instructions for the new branch:


Configuration for lazy.nvim:

```
return {
  "linux-cultist/venv-selector.nvim",
    dependencies = {
      "neovim/nvim-lspconfig", 
      "mfussenegger/nvim-dap", "mfussenegger/nvim-dap-python", --optional
      { "nvim-telescope/telescope.nvim", branch = "0.1.x", dependencies = { "nvim-lua/plenary.nvim" } },
    },
  lazy = false,
  branch = "regexp", -- This is the regexp branch, use this until its merged with the main branch later
  config = function()
      require("venv-selector").setup()
    end,
    keys = {
      { ",v", "<cmd>VenvSelect<cr>" },
    },
},
```

**Comment by linux-cultist** [comment]
Closing this since regexp branch will remember the activated venv for a specific directory. Please try it. :)

**Comment by kuator** [comment]
> Closing this since regexp branch will remember the activated venv for a specific directory. Please try it. :)

Thank, will do
