### ISSUE TITLE
Cannot discover the env created by micromamba

### ISSUE THREAD

**Issue by meicale** [linux-cultist/venv-selector.nvim#92]
I am using WSL on Windows11. Micromamba behaves similar to microconda and faster. When I use "VenvSelect" command, it can find the path such as "~/micromamba/envs/test/lib/python3.9/venv" but neovim complain can not find the env. Thank you!

**Comment by linux-cultist** [comment]
It's so many different venv managers now that Im thinking of rewriting the code that matches venvs to use regular expressions instead. It would allow for future venv managers to be supported by just adding a new regex. 

If I get some time soon, I will explore this option. :)

**Comment by linux-cultist** [comment]
There is a rewrite now in the `regexp`  branch that can easily find these venvs. It works by using regexp expressions to the fd command, so you basically just put the command together and when you are happy with what it finds, you put it in the plugin config.

You can read how it works in the Readme for the `regexp` branch, and feel free to try it out as well. It's still early days for it but it may work much better for you than the current main branch already.

**Comment by luyiyun** [comment]
@meicale Do you solve this problem?
