### ISSUE TITLE
Default `fd_binary_name` looks to be nil at present?

### ISSUE THREAD

**Issue by gwenwindflower** [linux-cultist/venv-selector.nvim#94]
Hi! I've been intermittently fighting with my config for this plugin for a few months, it's lovely (thank you for your excellent work!) but it was desperately slow for me, and I couldn't find anybody else complaining about it so I figured it was just me. I finally figured out what worked for me in digging through the plugins code -- it looks to me like the default config is now to set `fd_binary_name = nil`, while the docs say it points to `'fd'` -- i added that to my config (`fd_binary_name = 'fd'`) and voila! super speedy. I could totally be wrong here but wanted to flag it! Thanks again!

**Comment by gwenwindflower** [comment]
Just looked through utils file, I see what's happening more, I don't know why I had to specify it in my config 🤔 -- regardless, disregard, closing!

**Comment by zobayer1** [comment]
I can confirm this too. I had to add `fd_binary_name = "fd"` in the options.
